### ISSUE TITLE
File names are not properly escaped for RPM targets

### ISSUE THREAD

**Issue by jcbollinger** [jordansissel/fpm#1385]
While attempting to create an RPM package from a directory source on CentOS 7 Linux, I found that FPM 1.8.1 failed to properly escape one file name, with the result that rpmbuild failed.  The troublesome file was

`/opt/ccp4/ccp4-7.0/lib/treectrl2.2.10/htmldoc/What's New in TkTreeCtrl.html`

which FPM designated in the RPM spec file as

`/opt/ccp4/ccp4-7.0/lib/treectrl2.2.10/htmldoc/What's?New?in?TkTreeCtrl.html`

FPM logged the package build failure as

`{:timestamp=>"2017-07-27T09:57:28.604400-0500", :message=>"    File not found by glob: /tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68/BUILD/opt/ccp4/ccp4-7.0/lib/treectrl2.2.10/htmldoc/What's?New?in?TkTreeCtrl.html", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
{:timestamp=>"2017-07-27T09:57:28.604528-0500", :message=>"", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
{:timestamp=>"2017-07-27T09:57:28.604628-0500", :message=>"RPM build errors:", :level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}{:timestamp=>"2017-07-27T09:57:28.627912-0500", :message=>"Process failed: rpmbuild failed (exit code 1). Full command was:[\"rpmbuild\", \"-bb\", \"--define\", \"dist .el7.sjcrh\", \"--define\", \"buildroot /tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68/BUILD\", \"--define\", \"_topdir /tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68\", \"--define\", \"_sourcedir /tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68\", \"--define\", \"_rpmdir /tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68/RPMS\", \"--define\", \"_tmppath /tmp\", \"/tmp/package-rpm-build-3617cd577af5a35df9df913e3b23ec7adbb90474fcdf313f651b4f7a9c68/SPECS/ccp4-libs.spec\"]", :level=>:error, :file=>"fpm/command.rb", :line=>"491", :method=>"rescue in execute"}`

It appears that the problem is the apostrophe, for editing the problematic spec file line to

`/opt/ccp4/ccp4-7.0/lib/treectrl2.2.10/htmldoc/What\'s?New?in?TkTreeCtrl.html`

resolved the issue.  While I'm at it, however, I note that escaping would be a safer treatment than wildcards for the spaces in the file name, as wildcards could potentially defeat the effect of the `--exclude` option on files with similar names.

**Comment by jordansissel** [comment]
>  While I'm at it, however, I note that escaping would be a safer treatment than wildcards for the spaces in the file name

I agree, though the reason for fpm's complex escaping/wildcarding for rpm is because rpm has a history of not allowing me to actually specify these things.

What you describe now (`What\'s?New?in?TkTreeCtrl.html`) is news to me that it works; that is exciting! I've been frustrated many times by rpmbuild rejecting various attempts to include files by name where the files have spaces, quotes, etc.

Some details are in https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/rpm.rb#L173-L188

The reason for using `?` for spaces is that you need to `"quote the file"` when it has spaces (in my experience), and quoted file names do not support escapes or such, at least in my tests a while ago, so I asked rpm-list and was recommended to use wildcards. (http://lists.rpm.org/pipermail/rpm-list/2012-May/001161.html and other emails I can't find right now)

**Comment by jordansissel** [comment]
Some older/original references to the escaping/wildcarding dance that fpm does for rpmbuild are visible here:

https://github.com/jordansissel/fpm/blame/f4906879ca9114d3bb9a7f9c9be43bb09b75e8ab/templates/rpm.erb#L126-L146

**Comment by jordansissel** [comment]
I think adding an escaping entry for https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/rpm.rb#L178 to map `'` to `\'` should solve this problem.

**Comment by jcbollinger** [comment]
I confirm that adding an escaping entry solved the problem for me, after I realized that that involved updating not only the hash but also the gsub regex.  Here is the resulting overall statement:

    name = name.gsub(/(\ |\'|\[|\]|\*|\?|\%|\$)/, {
      ' ' => '?',
      "'" => "\\'",
      '%' => '[%]',
      '$' => '[$]',
      '?' => '[?]',
      '*' => '[*]',
      '[' => '[\[]',
      ']' => '[\]]'
    })

I speculate that other shell metacharacters not yet addressed there (e.g. <, >, ;) may need to be treated the same way, but I have not tested.

Since you remarked that this approach did not work with some older versions of RPM, I should specify that I'm using version 4.11.3, which is the one employed by CentOS 7, and I guess RHEL 7 and other EL7 variants.

**Comment by jcbollinger** [comment]
It looks like the above patch only partially fixed the issue with single quotes, and (unsurprisingly) it does not at all address related issues I have lately discovered with filenames containing double quote (`"`) and backslash (`\`) characters.  This prompted me to dive into the RPM sources to figure out what's going on.  It turns out to be a godawful mess.

Here are the details of `rpmbuild`'s relevant behavior:
- multiple whitespace-separated filenames can appear on the same line of the `%files` section of a spec, so whitespace inside filenames needs to be quoted or escaped by some means (FPM substitutes `?` characters to form globs)
- `rpmbuild` checks each filename read from the spec to determine whether it is a glob pattern, which it judges by the presence of _unescaped_ `*` or `?` characters, or a matched pair of unescaped `[` and `]` characters
- **if the name is determined not to be a glob** then it is used as-is (without escape processing, which makes escaping with `\` pretty broken in this case)
- **if the name is determined to be a glob** then it is processed via the POSIX `glob()` function, which performs quote and escape processing along with pattern expansion (so literal single quotes and double quotes and backslashes _need_ to be escaped in this case)

RPM seems also to allow whole filenames (but not partial ones) to be quoted with double quotes to suppress globbing and splitting at whitespace, but it does not seem to allow literal double quotes to appear within such a file name, escaped or not, so that feature is not so useful for FPM.

FPM can be made to deal with that without too much ugliness of its own.  I anticipate submitting offering a fix soon.

**Comment by jordansissel** [comment]
Related, I had wanted to try a trick I used years ago —

Since fpm puts all files into a temporary staging directory using BUILDROOT
or similar rpmbuild settings, it’s likely that the whole fpm %files section
could just use that path, like

%files
/

I haven’t tried this in over a decade, but if it works it’d be a complete
solution for any file name.

**Comment by jcbollinger** [comment]
FPM probably should not use `/`, as the resulting RPM then owns directories that it should not.  At least in some cases, however, it could use directories a little deeper.  Also, if FPM ever outputs file or directory names annotated via the `%attr`, `%dir`, or `%doc` macros, then that would complicate things.

In particular, my most common FPM use case is `--input-type dir --output-type rpm`, and for that, the source files and directories designated on the command line (as relocated, if applicable) would be a natural fit for the kind of directory-wise file-listing suggested.  And my particular directories are often huge, so if there is any performance advantage to be gained from letting RPM find files recursively instead of reading them from the spec file (and I bet there is) then I would really feel it.
